# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "317a3485160375756c2386951522cf3a"
name = "EmailWise Debug"
handle = "emailwise-debug"
application_url = "https://hold-uncle-lifetime-few.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3d7b636b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://hold-uncle-lifetime-few.trycloudflare.com/auth/callback",
  "https://hold-uncle-lifetime-few.trycloudflare.com/auth/shopify/callback",
  "https://hold-uncle-lifetime-few.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
